app/models.py
from hashlib import md5

from flask_login import UserMixin

from app import db, login


class User(UserMixin, db.Model):  # type: ignore
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    confirmed_email = db.Column(
        db.Boolean, nullable=False, default=False, server_default="f"
    )
    about_me = db.Column(db.String(140))

    def avatar(self, size: int) -> str:
        digest = md5(self.email.lower().encode("utf-8")).hexdigest()
        return f"https://www.gravatar.com/avatar/{digest}?d=identicon&s={size}"


@login.user_loader
def load_user(id: int) -> int:
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError

from app.models import User


class EditProfileForm(FlaskForm):
    about_me = TextAreaField("About me", validators=[Length(min=0, max=140)])
    submit = SubmitField("Submit")


class SettingsForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    submit = SubmitField("Submit")

    def __init__(self, original_username: str, *args, **kwargs) -> None:
        super(SettingsForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username: StringField) -> None:
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError("Please use a different username.")

app/__init__.py
import logging

from celery import Celery
from flask import Flask
from flask_admin import Admin
from flask_basicauth import BasicAuth
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import Config

admin = Admin(name="Homeland-Admin", template_mode="bootstrap3")
basic_auth = BasicAuth()
celery = Celery()
bootstrap = Bootstrap()
db = SQLAlchemy()
login = LoginManager()
login.login_view = "auth.login"
mail = Mail()
migrate = Migrate()


def create_app(config_class=Config) -> Flask:
    app = Flask(__name__)
    app.config.from_object(config_class)

    celery.main = app.name
    celery.conf.update(app.config)

    admin.init_app(app)
    basic_auth.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    login.init_app(app)
    mail.init_app(app)
    migrate.init_app(app, db)

    from app.auth import bp as auth_bp
    from app.errors import bp as errors_bp
    from app.main import bp as main_bp

    app.register_blueprint(auth_bp, url_prefix="/auth")
    app.register_blueprint(errors_bp)
    app.register_blueprint(main_bp)

    if not app.debug:  # pragma: no cover
        if app.config["LOG_TO_STDOUT"]:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.WARN)
            app.logger.addHandler(stream_handler)

    return app


from app import models  # noqa F401

app/main/__init__.py
from flask import Blueprint


bp = Blueprint("main", __name__)

from app.main import routes  # noqa F401

app/main/routes.py
from typing import Callable, Union

from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app import db
from app.main import bp
from app.main.forms import EditProfileForm, SettingsForm
from app.models import User


@bp.route("/", methods=["GET", "POST"])
@bp.route("/index", methods=["GET", "POST"])
@login_required
def index() -> str:
    return render_template("index.html")


@bp.route("/user/<username>")
@login_required
def user(username: str) -> str:
    user = User.query.filter_by(username=username).first_or_404()
    return render_template("user.html", user=user)


@bp.route("/edit_profile", methods=["GET", "POST"])
@login_required
def edit_profile() -> Union[str, Callable]:
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash("Your changes have been saved.")
        return redirect(url_for("main.user", username=current_user.username))
    elif request.method == "GET":
        form.about_me.data == current_user.about_me
    return render_template("edit_profile.html", title="Edit Profile", form=form)


@bp.route("/settings", methods=["GET", "POST"])
@login_required
def settings() -> str:
    form = SettingsForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.commit()
        flash("Your changes have been saved.")
    elif request.method == "GET":
        form.username.data == current_user.username
    return render_template("settings.html", title="Settings", form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %} {% block head %} {{super()}}
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" />
{% endblock %} {% block styles %} {{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
{% endblock %} {% block title %} Welcome Home {% endblock title %} {% block navbar %}
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button
        type="button"
        class="navbar-toggle collapsed"
        data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false"
      >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Homeland</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_anonymous %}
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
        {% else %}
        <li>
          <a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a>
        </li>
        <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% endblock navbar %} {% block content %}
<div class="container">
  {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
  <div class="alert alert-info" role="alert">{{ message }}</div>
  {% endfor %} {% endif %} {% endwith %} {% block app_content %}{% endblock %}
</div>
{% endblock %}

app/templates/edit_profile.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<h1>Edit Profile</h1>
<div class="row">
  <div class="col-md-4">
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock app_content %}

app/templates/index.html
{% extends "base.html" %} {% block app_content %}
<h1>Welcome, {{ current_user.username }}!</h1>

{% endblock %}

app/templates/settings.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<h1>Settings</h1>
<div class="row">
  <div class="col-md-4">
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock app_content %}

app/templates/user.html
{% extends "base.html" %}
{% block app_content %}
<table class="table table-hover">
  <tr>
    <td width="256px"><img src="{{ user.avatar(256) }}" /></td>
    <td>
      <h1>User: {{ user.username }}</h1>
      {% if user.about_me %}
      <p>{{ user.about_me }}</p>
      {% endif %} {% if user.username == current_user.username %}
      <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
      {% endif %}
    </td>
  </tr>
</table>
{% endblock %}